import type { AuctionResult } from './types';

/**
 * Mock auction results for prototype
 * Simulates data from Invaluable and LiveAuctioneers.
 * 
 * To integrate real data later:
 * - Invaluable: no public API; consider Apify, partnership, or ToS-compliant methods
 * - LiveAuctioneers: Apify scraper exists (paid); or partnership
 * - Add lib/dataSources.ts with fetchFromInvaluable(), fetchFromLiveAuctioneers()
 */
export const mockResults: AuctionResult[] = [
  {
    id: '1',
    title: 'Antique Chinese Blue and White Porcelain Vase, Kangxi Period',
    description: '18th century blue and white vase with floral motif',
    price: 2450,
    currency: 'USD',
    priceFormatted: '$2,450',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400',
    source: 'invaluable',
    sourceUrl: 'https://www.invaluable.com/search?query=blue+and+white+vases',
    auctionHouse: 'Doyle New York',
    lotNumber: '42',
    saleDate: '2025-01-15',
    category: 'blue-and-white porcelain pottery',
  },
  {
    id: '2',
    title: 'Pair of Blue and White Delft Vases, Dutch, 19th Century',
    description: 'Matching pair of tulip vases with cobalt blue decoration',
    price: 1200,
    currency: 'USD',
    priceFormatted: '$1,200',
    imageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400',
    source: 'liveauctioneers',
    sourceUrl: 'https://www.liveauctioneers.com/search/?q=blue+and+white+vases',
    auctionHouse: 'Skinner',
    lotNumber: '156',
    saleDate: '2025-01-10',
    category: 'blue-and-white delft pottery',
  },
  {
    id: '3',
    title: 'Blue and White Ming Style Porcelain Baluster Vase',
    description: 'Contemporary hand-painted reproduction',
    price: 185,
    currency: 'USD',
    priceFormatted: '$185',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400',
    source: 'invaluable',
    sourceUrl: 'https://www.invaluable.com/search?query=blue+and+white+vases',
    auctionHouse: 'Weschler\'s',
    lotNumber: '89',
    saleDate: '2025-01-08',
    category: 'blue-and-white porcelain pottery',
  },
  {
    id: '4',
    title: 'Chinese Export Blue and White Ginger Jar and Cover',
    description: '19th century export ware',
    price: 675,
    currency: 'USD',
    priceFormatted: '$675',
    imageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400',
    source: 'liveauctioneers',
    sourceUrl: 'https://www.liveauctioneers.com/search/?q=blue+and+white+vases',
    auctionHouse: 'Freeman\'s',
    lotNumber: '203',
    saleDate: '2025-01-05',
    category: 'blue-and-white chinese-export porcelain',
  },
  {
    id: '5',
    title: 'Large Blue and White Ceramic Floor Vase',
    description: 'Mid-20th century decorative vase',
    price: 320,
    currency: 'USD',
    priceFormatted: '$320',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400',
    source: 'invaluable',
    sourceUrl: 'https://www.invaluable.com/search?query=blue+and+white+vases',
    auctionHouse: 'Cowan\'s',
    lotNumber: '44',
    saleDate: '2025-01-03',
    category: 'blue-and-white pottery',
  },
  {
    id: '6',
    title: 'Antique Blue and White Meissen Style Vase',
    description: 'European porcelain, crossed swords mark',
    price: 1895,
    currency: 'USD',
    priceFormatted: '$1,895',
    imageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400',
    source: 'liveauctioneers',
    sourceUrl: 'https://www.liveauctioneers.com/search/?q=blue+and+white+vases',
    auctionHouse: 'Christie\'s',
    lotNumber: '78',
    saleDate: '2024-12-20',
    category: 'blue-and-white porcelain pottery',
  },
  {
    id: '7',
    title: 'Set of Three Blue and White Oriental Vases',
    description: 'Varying heights, famille bleu style',
    price: 450,
    currency: 'USD',
    priceFormatted: '$450',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=400',
    source: 'invaluable',
    sourceUrl: 'https://www.invaluable.com/search?query=blue+and+white+vases',
    auctionHouse: 'RR Auction',
    lotNumber: '112',
    saleDate: '2024-12-15',
    category: 'blue-and-white pottery',
  },
  {
    id: '8',
    title: 'Blue and White Staffordshire Pottery Mantel Vase',
    description: 'Victorian period, transfer printed',
    price: 275,
    currency: 'USD',
    priceFormatted: '$275',
    imageUrl: 'https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400',
    source: 'liveauctioneers',
    sourceUrl: 'https://www.liveauctioneers.com/search/?q=blue+and+white+vases',
    auctionHouse: 'Bonhams',
    lotNumber: '56',
    saleDate: '2024-12-10',
    category: 'blue-and-white pottery',
  },
];
